[package]
name = "shamir-sharing"
version = "0.1.0"
authors = ["Robert Habermeier <rphmeier@gmail.com>"]

[dependencies]
num = "0.1"
clap = { version = "2.26.0", features = ["yaml"] }
rand = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"